### ISSUE TITLE
Hi, Jack Summers

### ISSUE THREAD

**Issue by banjaminlee** [7CodeWizard/7CodeWizard#1]
I received your request just now.
How are you doing today?
I think you first followed me.
Anyway we can collaborate not only in github but also in our career as well.
I am always ready for a meeting?
I look forward to hearing from you soon. 
Jack Summers.
Why don't we contact through here?
I look forward your reply.

**Comment by 7CodeWizard** [comment]
nice to meet u
Where did u find my profile?

**Comment by banjaminlee** [comment]
Well, I think I found your profile while following the other developers.
How about collaboration?
What is your thought?

**Comment by 7CodeWizard** [comment]
Cool

**Comment by 7CodeWizard** [comment]
In which state are you located in?

**Comment by banjaminlee** [comment]
I am based in New York.
What about you?

**Comment by 7CodeWizard** [comment]
Awesome. Am located in Coventry, UK

**Comment by 7CodeWizard** [comment]
I found that you are beginner in web development, aren't u?

**Comment by 7CodeWizard** [comment]
Are you active on linkedin?
Why don't we contact on linkedin? or any other social platform?

**Comment by 7CodeWizard** [comment]
send me your linkedin url

**Comment by 7CodeWizard** [comment]
you are beginner, it's difficult to find a full-time employment as a swe

**Comment by banjaminlee** [comment]
Then what should I do right now?

**Comment by banjaminlee** [comment]
Do you know about Upwork?

**Comment by 7CodeWizard** [comment]
ofc

**Comment by 7CodeWizard** [comment]
don't u have linkedin?

**Comment by banjaminlee** [comment]
Well, I am not a senior, so I didn't create my linkedin profile.

**Comment by banjaminlee** [comment]
Hi, there?
Do you use Upwork account?

**Comment by banjaminlee** [comment]
??
what is this all about?
